### ISSUE TITLE
Azure Portal infrastructure setup for Upload API with tusd

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-upload#13]
### Azure Portal
- [X] 2022-10-05: DEX Storage Account
- [X] 2022-11-15: App Service #23
- [ ] APIM in Internal Subscription
- [ ] Routing to APIM (via OCIO > CDC FrontDoor)

**Comment by rmharrison** [comment]
2022-10-05; @boris-ning-usds added CSV team to AD so they have access to DEX Subscription Resource Group, including storage account (REQ0057512/RITM0057504)
