### ISSUE TITLE
Design downstream processing service

### ISSUE THREAD

**Issue by mkrystof** [CDCgov/data-exchange-upload#37]
Document has been posted to  https://teams.microsoft.com/_#/apps/d7958adf-f419-46fa-941b-1b946497ef84/sections/MyNotebook

Solution should be independent of bulk api solution

### Tasks
- [x] Define required metadata
- [x] Define partitioning scheme
- [x] Define queryable API for uploads (in progress, % uploaded, files uploaded by date range, filtering by program, date range, etc)
- [x] Define service functionality - copying files to a storage account and folder based on program, renaming files based on actual filename, partitioning files by date uploaded, etc.

**Comment by mkrystof** [comment]
## Metadata

All programs will be required to provide the following required metadata field:
- `meta_destination_id` - unique identifier used to indicate the program the upload is intended for.  It will be used to determine the required and optional metadata and to route the uploaded file to the indicated destination (program) for downstream processing.

### Program Specific Metadata 
Metadata should be configurable based on the program.  The `meta_destination_id` indicates which program the file belongs to and the configuration file for that program is used accordingly. The metadata config file contains:
```
[
	{
		"fieldname": "e.g. meta_ext_source",
		"allowed_values": "e.g. IZGW",
		"required": true|false,
		"description": "e.g. Indicates the metadata external source" 
	},
	...
]
```
> ### Note
> `allowed_values` is a comma seperated list of allowed values or null or empty string if any value is allowed\
> `required` if true the field is required, if false the field is optional\
> `description` is used for error/warning messages back to client if the metadata field is missing

### Metadata Configuration Files
Metadata configuration files will be used by the tusd [pre-create file hook](https://github.com/tus/tusd/blob/master/docs/hooks.md#pre-create), which is a blocking executable called before the file upload is accepted.  The pre-create executable can examine the metadata provided at the start of the upload and indicate to tusd whether the upload should be allowed to proceed or return an error to the client.

Example: **Routine Immunization** metadata

NDLP required metadata fields (none are optional)
- `meta_destination_id` = "RoutineImmunization"
- `meta_ext_source` = "IZGW"
- `meta_ext_sourceversion` = "V2022-09-09"
- `meta_ext_event` = "routineImmunization"
- `meta_ext_entity` = Submitting entity code, always 3 digits; e.g. NYA, CV1
- `meta_username` = Username of user who uploaded the file.  This will be the name of the service account if the upload is system-to-system.
- `meta_ext_objectkey` = UUID
- `meta_ext_filename` = Name of the file uploaded by the user.  File and extension should be named in accordance with guidelines outlined in the Data Use Agreement (DUA) for routine immunization.

> Metadata is typically provided as JSON by tus clients when the file is uploaded but is dependent on the tus client for the language used.

### Metadata Config File Location
> ### **Important!**
> Need to determine if a file volume can be mounted when the tusd server docker image is started.  If so, the metadata config files can be stored in an Azure blob storage container and used directly by tus file hooks factilitating easy management of metadata configurations by program.

### Metadata in Zipped Files

What if the file is a zip file?  Should the metadata be an array where there is one for each file? Or, should there be only one set of metadata for the zip that is applied to each of the files within the zip?  The latter doesn't seem advisable since metadata tends to be specific to a file, not a group of files.  For example, the meta_ext_objectkey in routine immunization.  It's conceivable some metadata could be generated by our system at time of upload, but that starts to complicate things. 

> **TO DO:** Decision needed whether we really want to support zipped files

## Blob Storage Partitioning Scheme

Partioning will be done by `program_id` -> `year` -> `month` -> `day` where year, month and day are the date the upload was performed.  The `program_id` will be a blob container whereas year, month and day will be folders within the program's container.

This partioning scheme allows us to easily see whether data for a particular day has been uploaded by program which aids in diagnostics.  Also, if we want to archive or delete old data the task is much easier when data is partioned this way.

## API
A queryable API is needed for uploads, including but not limited to status (e.g. in progress), % uploaded, files uploaded by date range, filtering by program, etc.

### API Data Source
Tus does not provide an API for retrieving upload status.  It does support HTTP calls to get the HEAD of an upload in progress or completed upload, but this is really intended for upload resume operations.  Tus also has a single GET call to retrieve metrics, but the output is in [Prometheus Text Format](https://github.com/tus/tusd/blob/master/docs/monitoring.md) and is intended for Prometheus clients.  Also, the metrics only give summary statistics and no information on the status of a particular upload or set of uploads.

However, tus does provide something called [hooks](https://github.com/tus/tusd/blob/master/docs/hooks.md) that can be used to receive events and influence tus upload behavior.  Included in the list of hooks is a non-blocking upload status event.  An executable can reside as a plugin on the tus server side to received these events and perform some action called tus "file hooks".  Alternatively, tus "HTTP hooks" can fire off HTTP POST events to a custom URL, which can listen for these and perform some action.

I propose we utilize a tus hook to persist upload statuses to an Azure SQL Server database.  In particular, the [`post-receive`](https://github.com/tus/tusd/blob/master/docs/hooks.md#post-receive) non-blocking hook.

**post-receive**

*This event will be triggered for every running upload to indicate its current progress. It will be emitted whenever the server has received more data from the client but at most every second. The offset property will be set to the number of bytes which have been transferred to the server, at the time in total. Please be aware that this number may be higher than the number of bytes which have been stored by the data store!*

Option 1: post-receive **file hook** runs locally on server
- Option 1a: post-receive event happens and tusd executes the `post-receive` script to post the event to an Azure service bus queue which is picked up by an Azure Function app that writes the upload status to an Azure SQL DB
- Option 1b: post-receive event happens and tusd executes the `post-receive` script on the server to write the upload status directly to Azure SQL DB

Option 2: post-receive **HTTP hook** calls custom URL
- Azure Function app provides the custom URL and is listening for the post-receive HTTP POST calls
- Function app writes the statuses to an Azure SQL DB when post-receive (upload status) is received

**Infrastructure needed by the API**
1. Azure Function App to receive the file upload status API HTTP requests
2. Access to the Azure SQL Server database that contains the upload statuses
3. If we go with Option 1a or Option 2 above we will also need an Azure Function App to process the `post-receive` upload status events

### Get Upload Status
Collection of API queries to provide bulk upload status.  The API will use the upload status Azure SQL DB mentioned above for its real-time data.

#### Get Upload Status for TGUID
- `GET https://bulk-upload.cdc.gov/status/<tguid>`\
    Provides upload status for a specific tguid.  tus clients are used to initiate the upload.  When the upload starts, clients are returned a unique identifer (tguid) used to resume uploads or identify the filename it is persisted as in blob storage once completed.  The tguid will be used for getting a specific uploaded file's status.
  
    JSON response example 1: Upload in progress
	```
	{
		"status": "Uploading",
		"percent_complete": 0.65,
		"file_name": "largefile.csv",
		"file_size_bytes": 190840042,
		"bytes_uploaded": 124046027,
		"tus_upload_id": "8923c9ff-6afa-42b2-a67b-89cb37e047e6",
		"time_uploading_sec": 34.4,
        "program_id": "RoutineImmunization"
	}
	```
    JSON response example 2: Upload completed
	```
    {
     	"status": "Completed",
     	"percent_complete": 100.0,
     	"file_name": "largefile.csv",
     	"file_size_bytes": 190840042,
        "bytes_uploaded": 190840042,
     	"tus_upload_id": "8923c9ff-6afa-42b2-a67b-89cb37e047e6",
     	"time_uploading_sec": 102.4,
        "program_id": "RoutineImmunization"
    }
	```

#### Get Upload Status for Program
- `GET https://bulk-upload.cdc.gov/status/program/{program_id}`\
	Provides all upload status for the given program id.

     Optional query parameters:
    - `date_start` = YYYYMMDDTTHHMMSSZ (UTC format, inclusive)
    - `date_end` = YYYYMMDDTTHHMMSSZ (UTC format, exclusive)
    - `page_size` = Integer indicating number of items per page
    - `page_num` = Integer indicating page to retrieve (1 based)

    JSON response example 1: Uploads for given date range
    ```
    [
        {
            "status": "Completed",
            "percent_complete": 100.0,
            "file_name": "largefile2.csv",
            "file_size_bytes": 190840042,
            "bytes_uploaded": 190840042,
            "tus_upload_id": "8b98c023-91d7-4f0e-8d9d-7d773327bccd",
            "time_uploading_sec": 98.2,
            "program_id": "RoutineImmunization"
        },
        {
            "status": "Uploading",
            "percent_complete": 0.65,
            "file_name": "largefile1.csv",
            "file_size_bytes": 190840042,
            "bytes_uploaded": 124046027,
            "tus_upload_id": "fb7ce04f-86a5-43c1-80b4-8a7398437e60",
            "time_uploading_sec": 34.4,
            "program_id": "RoutineImmunization"
        },
        {
            "status": "Completed",
            "percent_complete": 100.0,
            "file_name": "largefile3.csv",
            "file_size_bytes": 2908042,
            "bytes_uploaded": 2900042,
            "tus_upload_id": "c243ac89-d15b-488e-8fe2-d1f190b0ba6c",
            "time_uploading_sec": 7.4,
            "program_id": "RoutineImmunization"
        }
     ]
	 ```

## Downstream Services
The following functionality is needed to process uploaded files:
- Combine the tus uploaded file payload with its metadata.  The file metadata is stored in a separate .info file.
- Rename the uploaded file to its actual filename based on what is provided as the filename in the .info file.
- File is routed to the program specific container
- Copy the file from DeX storage account to EDAV storage account

> A single Azure Function App will be used for the first three bullets and the fourth done directly by Azure object replication.  More on object replication later down.

### Process Flow
1. Program A uploads a file via a tus client
2. Upload completes and shows up in the catch-all blob container of the DeX storage account
3. Azure `blob-create` event is triggered when the upload completes which is routed to an Azure event grid system topic 
4. An Azure Event Subscription to the event grid system topic triggers a Function app
5. Function app receives upload event and performs the following:
   - Combines the tus payload file with the .info file
   - Copies (routes) the file to a new DeX container based on program ID
6. File copied from Program A container in the DeX storage account to program A container in EDAV storage account.  For this simple copy operation we will utilize [Azure object replication](https://learn.microsoft.com/en-us/azure/storage/blobs/object-replication-overview).
   > Note the copy operations in object replication are setup 1:1 in terms of source container to destination container.

**Comment by mkrystof** [comment]
### Modification to Design
Azure Objection Replication will no longer be used.  Instead, the function app will take on this additional role.  There are two reasons for this.

First, Azure object replication requires that hierarchal naming is disabled.  With hierarchal naming disabled we will not be able to implement the partitioning scheme as designed where files are placed in subfolders by the year, month and day they were uploaded.  Partitioning by date in subfolders of the blob containers is important and not a design element we wish to forfeit.

Second, by performing the blob copy operation from the DeX storage account to the EDAV storage account we can provide a completely automatic and dynamic design.  With Azure Object Replication we would've had to add policies each time a new program and/or event type was added.  With it being part of the function app all this can all be automated and completely dynamic -- no updates or configuration necessary.

It is for these two reasons, partitioning and automated configuration, that the function app will do the blob copy from DeX to EDAV rather than Azure objection replication.
