### ISSUE TITLE
Quarterly Goal: FY23 Q2 (Jan-Mar 2023)

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-upload#41]
**Business goal**
Develop DEX Upload API for NCIRD quarterly immunization submissions, using compressed routine immunization files as the first use case (STLT --> IZ Gateway --> DEX --> NCIRD).
- The DEX Upload API will be able to receive, decompress files (as needed), and provide a basic pass/fail response to a single data submitter (IZ Gateway).
- These files will be uploaded to the EDAV environment, for data consumption by NCIRD
- At this time, a minimum level of record information will be provided back to the STLT via IZ Gateway.  

**Program Increment (PI) Goals**
- [ ] Build dev/tst/stg/prod of Upload API
  - [ ] Deploy DEX upload solution
  - [ ] Build function to "process" metadata (e.g., Tus upload metadata into Azure Storage metadata)
  - [ ] AuthN+Z for IZG to use DEX Upload API ==> @cfarmer-fearless  will ticket hang from epic #8
- [ ] EDAV storage
  - [ ] DEX to EDAV #47
  - [ ] EDAV to NDLP #54
- [ ] Onboarding IZ Gateway to DEX
  - [ ] Provide an onboarding environment (stg) for submitting entities to test prior to production submission.
- [ ] Provide basic feedback mechanism to STLT (STLT --> IZ Gateway --> DEX)

**Dependencies**
- CR in Azure GSS environment (SA&A received)
- Audacious Inquiry's ability to test with DEX on schedule

**Risks**
- Ability to instantiate dev/tst/stg/prod environments for Upload API

**Stretch Goals**
- [ ] Build dev/tst/stg/prod of Upload API
  - [ ] Build function to unzip

**Out of scope for this quarter**
- CSV Validation of routine immunization files (moved from stretch goals)
- Web Portal / GUI for either data submitters or data consumers
- Processing CSVs in EDAV (processing will be in NDLP)

--------------------
** DevSecOps Q2 **
Support the DEX Upload API team in lead up to an April release for the NCIRD RI use case.
[GSA CoE Cloud Reengineering FY23 Q2 Charter](https://cdc.sharepoint.com/:w:/r/teams/CDC-Data-Exchange/Shared%20Documents/Operations/DevOps/WS-5%20Charter%20-%20FY2023%20-%20Q2.docx?d=w034bbc2354a34fcd8fb14ed5ce5ff36d&csf=1&web=1&e=MVj04e)

** DevSecOps Q2 Goals**
- [ ] Infrastructure as Code built for 100% of cloud infrastructure
  - [ ] Development env
  - [ ] Staging env
  - [ ] Test env
  - [ ] Production env
- [ ] Receive SA&A using change request (CR) into Azure GSS environment (includes scanning)

** DevSecOps Dependencies **
- Upload API technical direction
- CST/OHMS - resource groups, vnets, subnets, ECPaaS, Akamai WAF
- Active Directory - DNS endpoints, AAD groups
- CSPO/Firewall - Splunk, DMZ, Firewalls, ZScaler
- ISSO/Security Steward - CR approval; security guidance; approval workflow
- EDAV - Databricks provisioning, endpoints
- IZ Gateway

** DevSecOps Risks **
- Upload API technical approach decision
- SA&A specs and ATO inheritance requirements in discovery
- Azure APIM and ownership of upload.api.gov

** DevSecOps Stretch Goals **
- [ ] Continuous Integration (CI) pipeline set up with manual deployments (app codebase, static/dynamic scans, integration with scanning tools in use)

** DevSecOps Assumptions **
- Terraform automation will be completed by end of December 2022
- Upload API technical approach will be decided by end of December 2022
- For Q2 work and Q3 April release, NCIRD-RI use case will not include CSV validation pipeline

** DevSecOps Out of Scope for this quarter **
- Continuous Delivery (CD) pipeline set up to dev/stg/tst/prd
- DEX runbook created and updated
- CDC SAMS integration with Azure APIM

**Comment by lmcnabb** [comment]
@rmharrison can you review/edit?
