### ISSUE TITLE
Sprint Goal: Feb 23 to Mar 8

### ISSUE THREAD

**Issue by jmann2817** [CDCgov/data-exchange-upload#65]
Goal
- [ ] EDAV to NDLP #54
- [x] Conversation with EDAV about their metastore plans
- [x] Spike on metastore #64
- [x] Supplemental API #68
- [x] Supplemental API #67
- [x] Verify that IZG can invoke the DeX API in stg. #58

Stretch goals
- [ ] Java client #66
