### ISSUE TITLE
Create tus hooks for providing upload status in Azure Cosmos

### ISSUE THREAD

**Issue by mkrystof** [CDCgov/data-exchange-upload#67]
### Overview
The purpose of this task is to provide upload status to a persistent queryable storage in order for an API to retrieve upload status.  tus provides hooks for receiving upload status as uploads occur as well as when they are terminated.  The goal here is to receive those tus hook events and provide the information to Cloud storage, namely Azure Cosmos, which will provide a very convenient backing store for a RESTful API to be implemented.

### Subtasks

- [x] Create tus hook for receiving post-receive events (upload received status)
- [x] Create tus hook for receiving post-terminate events (upload terminated)
- [x] Define Cosmos DB table for upload events
- [x] Create service to maintain connection from tusd to Azure Cosmod to govern upload events
