### ISSUE TITLE
Implement supplemental upload API function app

### ISSUE THREAD

**Issue by mkrystof** [CDCgov/data-exchange-upload#68]
### Overview
A supplemental API will provide queryable upload status.  See the parent epic for detailed requirements of the API.

### Subtasks
- [x] Create open api spec for the supplemental API
- [x] Create Azure function app (isolated) for the supplemental API.  A persistent connection to Azure Cosmos will be used to ensure efficiency and performance across web api calls, which all need access to query the Cosmos DB.
- [x] Implement Supplemental API app service in Kotlin Micronaut.
