### ISSUE TITLE
Sprint Goals May 4th - May 17th 

### ISSUE THREAD

**Issue by jmann2817** [CDCgov/data-exchange-upload#86]
**Sprint Goals:**
- [x] Continue to develop test plan - Nadia
    - [x] Get access to EDAV storage account
    - [x] Add steps to include EDAV verification 
- [x] Review Update DEX Upload API document for supplemental API (planned for 1.1) - Shu #69  (1.1 draft is done. will create a new ticket to add changes)
     - [x] Review current API design with Cosmin - Matt 
     - [x] Ask Shu to review after Cosmin
- [ ] Test tus file-hook for post-terminate - Matt  #76 
- [ ] Standup staging environment - Anand
- [ ] #92
- [ ] Verification/QA staging environment - Nadia
- [x] PulseNet support - Cosmin #89
- [ ] Stress/load testing - Cosmin/Matt/Chase #88
- [x] Terraform for dev env (Done but working through a bug that is being tracked on the devops board)
    - [x] #90
    - [x] #91
- [ ] APIM wired up to Supplemental API - Anand/Chase
    - [x] Consolidate source of truth to openapi spec for configuring APIM - Chase
    - [x] Determine what repo openapi specs will live (needs to be public) - Chase
    - [ ] Troubleshoot issues with supplemental api <-> APIM connectivity
- [x] Automated testing research - PoC for automated integration testing for Upload API - Chase/Chris
- [x] CI/CD design final decision - Chase/Team
- [x] Define SAMS scopes for authZ and how that ties in with APIM authZ - Matt/Chase #87
- [x] Add influenza event type to the config for NDLP - Matt
     - [x] Deploy to DEV
     - [ ] Test in EDAV (Nadia)
