### ISSUE TITLE
Sprint Goal May 18th - May 31st 

### ISSUE THREAD

**Issue by jmann2817** [CDCgov/data-exchange-upload#95]
**Sprint Goals:**
- [ ] Test tus file-hook for post-terminate - Matt  #76 
- [ ] Standup staging environment - Anand  
- [x] #92
- [ ] Verification/QA staging environment - Nadia
- [ ] Deploy PulseNet #89
- [ ] Stress/load testing - Cosmin/Matt/Chase #88
- [ ] APIM wired up to Supplemental API - Anand/Chase
    - [ ] Troubleshoot issues with supplemental api <-> APIM connectivity
- [x] Add influenza event type to the config for NDLP - Matt
     - [ ] Test in EDAV (Nadia) 
 - [ ] AIMS support for onboarding #94
 - [ ] PulseNet testing support for local host https #96
 

**Notes**
Will stage be ready on 6/6/2023 for PulseNet? UAT is planned to start on 6/12/2023. 

NCIRD Submissions
ENV: PROD
1-30 Apr 2023: Routine Immunization, submission period
Target submitters, N=4
Actual submitters: Nevada

 1-9 June 2023: Flu Immunization, submission period
Target submitters, N=5

 1-31 July 2023: Routine Immunization, submission period
Target submitters, N=5
